// <auto-generated />
using CICD_Uppgift1.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CICD_Uppgift1.Migrations
{
    [DbContext(typeof(MyDatabase))]
    [Migration("20211004190818_added composite key for RequestPoll table2")]
    partial class addedcompositekeyforRequestPolltable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("CICD_Uppgift1.Models.AdminAccount", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.ToTable("AdminAccounts");
                });

            modelBuilder.Entity("CICD_Uppgift1.Models.RequestPoll", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldRole")
                        .HasColumnType("TEXT");

                    b.Property<int>("OldSalary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username", "Salary", "Role");

                    b.ToTable("RequestPolls");
                });

            modelBuilder.Entity("CICD_Uppgift1.Models.UserAccount", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
